# Generated by Django 4.1.7 on 2023-08-02 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_coupon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='address',
            new_name='addressLine1',
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='addressLine2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='subCity',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
