# Generated by Django 4.1.7 on 2023-08-02 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_shippingaddress_provive'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='addressLine1',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='addressLine2',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='provive',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='subCity',
        ),
    ]
