# Generated by Django 4.1.7 on 2023-08-02 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_rename_addressline1_shippingaddress_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='provice',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='subCity',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
