# Generated by Django 3.2.1 on 2023-09-17 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_product_default_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='code',
            new_name='coupon_code',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='discount_percentage',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='expiration_date',
        ),
        migrations.AddField(
            model_name='coupon',
            name='discount_price',
            field=models.IntegerField(default=5000),
        ),
        migrations.AddField(
            model_name='coupon',
            name='is_exprired',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='coupon',
            name='minimum_amount',
            field=models.IntegerField(default=15000),
        ),
    ]
